services:
  web:
    build: ./py
    container_name: flask_app
    ports:
     - "5000:5000"
    volumes:
      - ./py:/py  # 👈 Mount local source code into container
    environment:
      - FLASK_ENV=development  # 👈 Enables auto-reload and debug mode
    networks:
      - app-network


  nginx:
    image: nginx:latest
    container_name: nginx_proxy
    ports: 
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./selfsigned.crt:/etc/nginx/certs/selfsigned.crt:ro
      - ./selfsigned.key:/etc/nginx/certs/selfsigned.key:ro
    depends_on:
      - web 
    networks: 
      - app-network 

networks:
  app-network:
    driver: bridge
    