version: "3.8"

services:
  nginx:
    image: nginx:latest
    container_name: mynginx
    ports:
      - "8080:80"
    volumes: 
      - ./html:/usr/share/nginx/html:ro
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    restart: unless-stopped